<?php

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['MSC']['noUniversalPaymentSelect'] 	= 'Bitte erstellen Sie ein Auswahlfeld für die Zahlungsmethode.';
$GLOBALS['TL_LANG']['MSC']['noActivePaymentMethods'] 	= 'Kein Bezahlsystem-Formularfeld angelegt oder sichtbar';
$GLOBALS['TL_LANG']['MSC']['sessionEnded']				= 'Ihre Session wurde beended bitte laden Sie die Seite neu oder melden Sie sich erneut an.';

/**
 * Content elements
 */
$GLOBALS['TL_LANG']['CTE']['universalpayment_node']		= 'Bezahlsystem';
$GLOBALS['TL_LANG']['CTE']['universalpayment']    		= array('Bezahlsystem','Universelle Schnittstelle für Bezahlsysteme');

/**
 * Modules
 */
$GLOBALS['TL_LANG']['FMD']['universalpayment_node'] = 'Bezahlsystem';
$GLOBALS['TL_LANG']['FMD']['universalpayment'] = array('Bezahlsystem','Universelle Schnittstelle für Bezahlsysteme');