<?php

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_content']['universalPaymentMethod'] 		= array('Zahlungsmodul','Bitte wählen Sie das Zahlungsmodul aus.');
$GLOBALS['TL_LANG']['tl_content']['universalPaymentTemplate'] 		= array('Formular-Template','Bitte wählen Sie das Ausgabetemplate aus.');
	
/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_content']['payment_legend'] 				= 'Zahlungssystem';
$GLOBALS['TL_LANG']['tl_content']['payment_setting_legend'] 		= 'Zahlungsmodul-Einstellungen';
$GLOBALS['TL_LANG']['tl_content']['template_legend'] 				= 'Template Einstellungen';
$GLOBALS['TL_LANG']['tl_content']['expert_legend'] 					= 'Experten-Einstellungen';
