<?php

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Form fields
 */
$GLOBALS['TL_LANG']['FFL']['universalpayment']							= array('Bezahlsystem', 'Aktiviert ein Bezahlsystem für ein Formular');
$GLOBALS['TL_LANG']['FFL']['universalpayment_select']					= array('Bezahlsystem Frontend Auswahl', 'Stellt eine Auswahl im Frontend für die aktivierten Bezahlsysteme bereit');

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_form_field']['universalPaymentMethod'] 			= array('Zahlungsmodul','Bitte wählen Sie das Zahlungsmodul aus.');
$GLOBALS['TL_LANG']['tl_form_field']['universalPaymentModulePublished']	= array('Modul aktivieren','Bitte wählen Sie hier um das Modul zu aktivieren.');
$GLOBALS['TL_LANG']['tl_form_field']['universalPaymentSelectIsRadio']	= array('Als Radio-Button darstellen','Bitte wählen Sie hier um das Widget als Radio-Button-Menü darzustellen (Standard: Select-Menü)');
$GLOBALS['TL_LANG']['tl_form_field']['universalPaymentAddJumpTo']		= array('Weiterleitung auf Unterseite','Wählen Sie die Zielseite, die nach dem Absenden des Formulars aufgerufen wird. Diese Seite enthält in der Regel einen Bezahl-Button als Module oder Inhaltselement. Hinweis: Diese Einstellung überschreibt die Weiterleitungsseite in den Formular-Einstellungen. Ein Formularfeld vom Typ Bezahlsystem-Auswahl muss im Formular angelegt sein.');
$GLOBALS['TL_LANG']['tl_form_field']['universalPaymentJumpTo']			= array('Zielseite für dieses Bezahlmodul','Wählen Sie die Weiterleitungsseite. In der Regel befindet sich dort ein Bezahlformular als Module oder Inhaltselement.');
$GLOBALS['TL_LANG']['tl_form_field']['universalPaymentAddSettings']		= array('Einstellungen für Direktweiterleitung','Wählen Sie wenn Sie die direkte Weiterleitung des Formulars zu dem Bezahlanbieter aktivieren wollen.');
	
/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_form_field']['payment_legend'] 					= 'Zahlungssystem';
$GLOBALS['TL_LANG']['tl_form_field']['payment_setting_legend'] 			= 'Zahlungsmodul-Einstellungen';
$GLOBALS['TL_LANG']['tl_form_field']['template_legend'] 				= 'Template Einstellungen';
$GLOBALS['TL_LANG']['tl_form_field']['expert_legend'] 					= 'Experten-Einstellungen';
